# Site information
site_name: 'Haskell Notes'

# Repository information
repo_name: 'jieyouxu/Haskell-Notes'
repo_url: 'https://github.com/jieyouxu/Haskell-Notes'

# Navigation order
nav:
  - 'Home': 'index.md'
  - 'Foundation': '1-foundation/notes.md'
  - 'Haskell Basics': '2-haskell-basics/notes.md'
  - 'Strings': '3-strings/notes.md'
  - 'Basic Datatypes': '4-basic-datatypes/notes.md'
  - 'Types': '5-types/notes.md'
  - 'Typeclasses': '6-typeclasses/notes.md'
  - 'Functional Patterns': '7-functional-patterns/notes.md'
  - 'Recursion': '8-recursion/notes.md'
  - 'Lists': '9-lists/notes.md'
  - 'List Folding': '10-folding-lists/notes.md'
  - 'Algebraic Datatypes': '11-algebraic-datatypes/notes.md'
  - 'Handling Exceptions': '12-handling-exceptions/notes.md'
  - 'Building Projects': '13-building-projects/notes.md'
  - 'Monoids, Semigroups': '15-monoids-semigroups/notes.md'
  - 'Functors': '16-functors/notes.md'
  - 'Applicatives': '17-applicatives/notes.md'
  - 'Monads': '18-monads/notes.md'
  - 'Foldable': '20-foldable/notes.md'
  - 'Traversable': '21-traversable/notes.md'
  - 'Y Combinator': 'misc/y-combinator.md'

# Theme
theme:
  name: 'material'
  language: 'en'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/favicon.ico'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'deep purple'
    accent: 'pink'
  feature:
    tabs: false

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# JavaScript
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
